### PR TITLE
Feature/coraltpu support

### PR DESCRIPTION
**Pull request by guillemmateos**

### CODE REVIEW

**Comment by guillemmateos** [comment]
This PR adds support for Coral TPU to the detect_service. I will be submitting PRs to the other relevant repos to complete support.

**Comment by mehmetgoren** [comment]
That's fantastic! Thank you for incorporating Coral TPU support into the project. I'll be taking care of other tasks such as UI integration, Docker support, and any other relevant work.

**Comment by guillemmateos** [comment]
Thanks for creating Feniks which is a fantastic piece of software! I've sent a PR also for the webapp that adds support for the 2 relevant configs that may at some point be changed (the model and labels) although i only bundled one model right now on the container.

I did also submit a PR for the docker-compose creator so it takes care of the Coral bits.

I may have missed something though as there's quite a few repos and quite some code to go through, but so far on my testing I get the detections done properly and the CPU on an i5-7600U for the OD is close to 0 (main CPU hog when using Coral is then the ffmpeg service, not sure if there's a way to optimize that as it seems to be using quite some CPU)

**Comment by mehmetgoren** [comment]
Yes, capturing screenshots with FFmpeg consumes excessive CPU time. If there is a way to mitigate this performance cost, please let me know.

**Comment by guillemmateos** [comment]
> Yes, capturing screenshots with FFmpeg consumes excessive CPU time. If there is a way to mitigate this performance cost, please let me know.

The ffmpeg process seems to use quite a lot of CPU even when nothing is being detected. What is ffmpeg being used for between containers? I could see there are multiple processes running even if there's only one camera so i suspect data gets reencoded or something? I did try to figure it out but there's many containers and quite a lot of code and I thought it would be easier to ask :)

**Comment by mehmetgoren** [comment]
If you enable the AI snapshot service for a camera, first, FFmpeg decodes the frame and then writes the complete image to the pipe. Afterwards, the data is read and fitted into a numpy array. These operations are repeated every second (if you specify FPS as 1, which is the default) and consume a significant amount of CPU time. However, it is worth noting that a single Raspberry Pi 4 unit can easily handle snapshot operations for six cameras, so I believe the performance penalty is acceptable. If you want to learn more about this, here is the link to the code: 
https://github.com/mehmetgoren/ffmpeg_service/blob/c8347a63cbde04ef4899362f0a8c4286aceadbcd/readers/ffmpeg_pipe_reader.py

However, if there is a more efficient way to accomplish this, I would be very interested in learning about it.

**Pull request merged**
